"""rename address

Revision ID: 6154a7bcad34
Revises: af28d396297f
Create Date: 2024-10-01 16:28:46.434756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6154a7bcad34'
down_revision = 'af28d396297f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
